;<?php //security line
;die(); //security line
;/* //security line

[DB]
host = "127.0.0.1"
schema = "INFORMATION_SCHEMA"
user = "root"
password = "root"
charset = "utf8"

[GOOGLE_API]
; JSON file generated by the Google API console
json_config_file = "auth.json"
; This ID can be found in the spreadsheet URL
spreadsheet_id = "741RxLp94czSaFmN-MLmXQYma3pfqjIPDzin2taHvxNA"
spreadsheet_range = "Sheet1!B2:ZZ"

; Define the scope as SPREADSHEETS for read/write or SPREADSHEETS_READONLY for read
spreadsheet_scope = "SPREADSHEETS"

; RAW: The input is not parsed and is simply inserted as a string
; USER_ENTERED: The input is parsed exactly as if it were entered into the Google Sheets UI
spreadsheet_input_option = "USER_ENTERED" 

[MISC]
sql_file = "script.sql"

;*/ //security line
